name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

variables:
  - group: epsat


jobs:
  - job: epsat_build_and_deploy
    displayName: Build & Deploy
    timeoutInMinutes: 30
    pool:
      name: 'AWS-ECS'
    workspace:
      clean: all
    steps:
      - bash: |
          sudo apt-get -yq install heroku
        displayName: Install Heroku

      - bash: |
          cd $(Build.Repository.LocalPath)
          export HEROKU_API_KEY=$(HEROKU_API_KEY)
          heroku git:remote -a nhsd-epsat
          git push heroku master:master
        displayName: Build & Deploy

