trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

pr:
  branches:
    include: ['*']

steps:
- script: zip handler.zip handler.py
  displayName: 'zip the handler function for the release'

- script: mkdir dist; mv handler.zip dist/handler.zip
  displayName: 'create a dist folder'

- script: mv handler.zip dist/handler.zip
  displayName: 'move handler files into dist'

- script: mv main.tf dist/main.tf
  displayName: 'move main terraform file into dist'

- script: mv variables.tf dist/variables.tf
  displayName: 'move required variable file into dist'

- publish: dist/
  artifact: eps-steel-thread