trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

pr:
  branches:
    include: ['*']

steps:
- script: zip handler.zip handler.py
  displayName: 'zip the handler function for the release'

- script: mkdir dist
  displayName: 'create a dist folder'

- script: mkdir dist/client
  displayName: 'create a client folder'

- script: mv handler.zip dist/handler.zip; mv client/** dist/client; mv main.tf dist/main.tf; mv variables.tf dist/variables.tf;
  displayName: 'move required files into dist'

- publish: dist/
  artifact: eps-steel-thread