trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

pr:
  branches:
    include: ['*']

steps:
- script: sudo apt update
  displayName: 'Update OS'

- script: sudo apt install python3-setuptools
  displayName: 'Install setuptools'

- script: pip3 install --user pipenv
  displayName: 'install pipenv'

- script: python3 -m pipenv install --dev
  displayName: Install dependencies

- script: python3 -m pipenv run pytest -v
  displayName: Run tests in python package

- bash: sh ./scripts/bundle_python.sh
  displayName: Create python deployment package

- script: mkdir dist
  displayName: 'create a dist folder'

- script: mkdir dist/client
  displayName: 'create a client folder'

- script: mv handler.zip dist/handler.zip
  displayName: 'move handler files into dist'
  
- script: mv client/** dist/client
  displayName: 'move client files into dist'

- script: mv main.tf dist/main.tf
  displayName: 'move main terraform file into dist'

- script: mv variables.tf dist/variables.tf
  displayName: 'move required variable file into dist'

- script: scripts/build_proxy.sh
  displayName: 'build proxy'

- script: cp -R build/. dist/
  displayName: 'Copy build to dist'

- script: cp -R terraform dist
  displayName: 'Copy proxy terraform'

- publish: dist/
  artifact: eps-steel-thread