"""Initial

Revision ID: e7a00d0217d4
Revises: 
Create Date: 2021-05-28 00:47:42.693228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a00d0217d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prepare_request',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prepare_response',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('send_request',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('send_request')
    op.drop_table('prepare_response')
    op.drop_table('prepare_request')
    # ### end Alembic commands ###
